# Generated by Django 2.2.1 on 2021-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Autor activo'),
        ),
    ]
